version: '2'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    command: bundle exec foreman start
    volumes:
      - .:/grader
    ports:
      - "3000:3000"
    links:
      - db 